# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog
email: hamudazabad@gmail.com
description:  This is a small blog I have created for my Image Processing class. Here I will post about the work that I have done in and out of class.
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "https://thezoomlesss.github.io" # the base hostname & protocol for your site
github_username:  thezoomlesss

# Build settings
markdown: kramdown
